export * from './admin.api';
import { AdminApi } from './admin.api';
export * from './config.api';
import { ConfigApi } from './config.api';
export * from './health.api';
import { HealthApi } from './health.api';
export * from './reviews.api';
import { ReviewsApi } from './reviews.api';
export * from './training.api';
import { TrainingApi } from './training.api';
export const APIS = [AdminApi, ConfigApi, HealthApi, ReviewsApi, TrainingApi];
