/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One class of abstention, and what to do about it.  See `webapp.abstentions`. The client renders what it is handed: it carries no copy of a reason string and makes no judgement of its own about whether a rule was right to stand down.
 */
export interface AbstentionKindInfo { 
    /**
     * What would fix it, written for whoever is reading the review.
     */
    guidance: string;
    help: string;
    key: string;
    label: string;
    /**
     * Whether offering to propose a fix makes sense for this class. False where the abstention was correct, or the operator asked for it.
     */
    proposable: boolean;
}

