/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A root cause that would account for several abstentions at once.  Drawn entirely from two things already on the job record — what the rules said, and what `webapp.pdfkind` found in the file. Never a certainty, and the text never phrases it as one: the sheets it names are the reader\'s way of checking the claim rather than taking it on trust.
 */
export interface AbstentionDiagnosis { 
    /**
     * What to do about it, in the imperative.
     */
    action: string;
    detail: string;
    headline: string;
    key: string;
    /**
     * Whether re-running the review would test the theory. The client offers the re-run only where this is true.
     */
    rerun: boolean;
    /**
     * Rule ids this would account for.
     */
    rules?: Array<string>;
    /**
     * Sheets to look at, numbered from 1 as the viewer numbers them.
     */
    sheets?: Array<number>;
}

