/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A rule that declined to run. Never the same thing as a rule that passed.
 */
export interface Abstention { 
    detail?: string;
    reason: string;
    rule: string;
}

