/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MailStatus } from './mail-status';


export interface AdminOverview { 
    active_version: number;
    assist: string;
    calibrated_rules: number;
    /**
     * Open feedback by disposition.
     */
    counts: { [key: string]: number; };
    github: string;
    mail: MailStatus;
    open_feedback: number;
}

