/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Counts only — never the reviewer\'s notes. See `fbcreview/ai/review.py`.
 */
export interface AiReviewSummary { 
    max_passes: number;
    model: string;
    /**
     * Notes left for the audit record; kept with the job.
     */
    notes: number;
    /**
     * Why the loop stopped: meets_request, max_passes, no_change, nothing_to_reread, review_failed or reread_failed. The last pass\'s result stands in every case.
     */
    outcome: string;
    /**
     * Runs of the rules, the first included. At most 3.
     */
    passes: number;
    prompt_version: string;
    /**
     * Checks the reviewer completed.
     */
    reviews: number;
    sheets_reread: number;
    usage?: { [key: string]: number; };
}

