/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Counts only — never the reviewer\'s notes. See `fbcreview/ai/review.py`.
 */
export interface AiReviewSummary { 
    edits_applied?: number;
    /**
     * Edits not applied — a quote not found on the sheet, an unknown key.
     */
    edits_rejected?: number;
    findings_added?: number;
    findings_revised?: number;
    /**
     * Each is also an abstention saying it was withdrawn.
     */
    findings_withdrawn?: number;
    max_passes: number;
    model: string;
    /**
     * Notes left for the audit record; kept with the job.
     */
    notes: number;
    /**
     * Why the loop stopped: meets_request, max_passes, no_change, review_failed or reread_failed. The last good state stands in every case.
     */
    outcome: string;
    /**
     * AI passes run — check, edit, verify. At most 3.
     */
    passes: number;
    prompt_version: string;
    /**
     * Passes the reviewer completed.
     */
    reviews: number;
    /**
     * Runs of the rules, the first included.
     */
    rule_runs?: number;
    sheets_reread: number;
    usage?: { [key: string]: number; };
}

