/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Counts only — never sheet text. See `fbcreview/ai/readings.py`.
 */
export interface AiReadingSummary { 
    /**
     * Proposals found on the sheet and used.
     */
    accepted: number;
    model: string;
    prompt_version: string;
    /**
     * Values the model proposed.
     */
    proposals: number;
    /**
     * Proposals the sheet did not bear out; never used.
     */
    rejected: number;
    sheets_failed: number;
    sheets_read: number;
    usage?: { [key: string]: number; };
}

