/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What `webapp.assist` made of a free-text comment.  Recorded so the owner can see what was said about their user\'s words, and typed so the client can show it. Advisory in the strict sense: the triage may raise a disposition on the strength of it and may never lower one.
 */
export interface AssistOpinion { 
    aspect?: string;
    confidence?: AssistOpinionConfidenceEnum;
    names_a_code_section?: boolean;
    rationale?: string;
    summary: string;
    verdict?: string;
}
export enum AssistOpinionConfidenceEnum {
    Low = 'low',
    Medium = 'medium',
    High = 'high'
};



