/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What reading a drawing upload produced, in counts.  Reported for the same reason `ConversionReport` is: a drawing with eight layouts that plotted to two sheets is a thin review, and the person needs to see why. Counts only — no layer names, no attribute text — because this sits on the job record, and the drawing\'s content lives in the bucket.
 */
export interface CadReport { 
    /**
     * Block attributes read with their tags.
     */
    attributes?: number;
    /**
     * Facts the engine took from the drawing itself (block attributes that name a catalog field), each saying it came from the drawing.
     */
    claims?: number;
    /**
     * The DWG converter and its version; empty when none ran (a DXF).
     */
    converter?: string;
    /**
     * Dimensions read, with printed text and measured length.
     */
    dimensions?: number;
    /**
     * Drawing files read (a zip may hold several).
     */
    drawings?: number;
    /**
     * What was uploaded: `dwg`, `dxf` or `zip`.
     */
    format: CadReportFormatEnum;
    /**
     * Layers in the drawings\' own layer tables.
     */
    layers?: number;
    /**
     * The plotter\'s version.
     */
    render_version?: string;
    /**
     * Time spent converting and plotting.
     */
    seconds?: number;
    /**
     * Pages plotted: one per paper-space layout with something on it, or model space when a drawing has no layouts.
     */
    sheets?: number;
    /**
     * Sheets whose number was read from a title-block field that says it is the sheet number. A layout\'s tab name is never taken for one.
     */
    sheets_identified?: number;
    /**
     * Viewports onto model space, each with its exact scale.
     */
    viewports?: number;
    /**
     * What could not be read, in prose: a zip member skipped and why, text that could not be placed, an xref that was not supplied.
     */
    warnings?: Array<string>;
}
export enum CadReportFormatEnum {
    Dwg = 'dwg',
    Dxf = 'dxf',
    Zip = 'zip'
};



