/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One lever, published so the admin console hard-codes no list.
 */
export interface CalibrationKnob { 
    bounds?: Array<number> | null;
    choices?: Array<string> | null;
    help: string;
    kind: CalibrationKnobKindEnum;
    name: string;
}
export enum CalibrationKnobKindEnum {
    Bool = 'bool',
    Int = 'int',
    Float = 'float',
    Severity = 'severity',
    Strings = 'strings'
};



