/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One finding this profile actually changed.
 */
export interface CalibrationAdjustment { 
    after: string;
    before: string;
    detail?: string;
    fid: string;
    knob: string;
    rule_id: string;
}

