/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One lever moved on one rule, with why.
 */
export interface CalibrationChange { 
    knob: string;
    note?: string;
    reason?: string;
    rule_id: string;
    /**
     * The value this change sets, rendered for display.
     */
    value?: string;
}

