/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RuleCalibration } from './rule-calibration';


/**
 * A versioned set of rule calibrations. Versions are immutable.
 */
export interface CalibrationProfile { 
    created_at?: string | null;
    created_by?: string;
    derived_from?: number | null;
    edition: string;
    label: string;
    note?: string;
    owner_uid?: string;
    profile_id: string;
    rules?: { [key: string]: RuleCalibration; };
    scope: string;
    version: number;
}

