/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalibrationProfile } from './calibration-profile';
import { CalibrationKnob } from './calibration-knob';


/**
 * The admin console\'s calibration screen.
 */
export interface CalibrationView { 
    active: CalibrationProfile;
    knobs: Array<CalibrationKnob>;
    /**
     * Approved-and-not-yet-promoted proposals. Always 0 today: accepting a proposal promotes it.
     */
    pending: number;
    versions: Array<CalibrationProfile>;
}

