/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalibrationAdjustment } from './calibration-adjustment';


/**
 * What the overlay did to a review. Part of the audit trail.  Recorded whether or not anything moved: a review that says \"profile v4, nothing adjusted\" is a different statement from a review that never mentions calibration at all.
 */
export interface CalibrationReport { 
    adjusted: number;
    adjustments?: Array<CalibrationAdjustment>;
    profile_id: string;
    profile_label: string;
    profile_version: number;
    suppressed: number;
}

