/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewOptions } from './review-options';
import { OccupancyGroup } from './occupancy-group';
import { MailStatus } from './mail-status';
import { Edition } from './edition';


export interface ConfigResponse { 
    defaults: ReviewOptions;
    editions: Array<Edition>;
    mail: MailStatus;
    max_pages: number;
    max_upload_mb: number;
    occupancy_groups: Array<OccupancyGroup>;
    retain_days: number;
    /**
     * Rule ids registered in this build.
     */
    rules: Array<string>;
    /**
     * Severity floor choices, most severe first.
     */
    severities: Array<ConfigResponseSeveritiesEnum>;
    /**
     * Ordered stage labels a running job moves through.
     */
    stages: Array<string>;
}
export enum ConfigResponseSeveritiesEnum {
    Critical = 'CRITICAL',
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW'
};



