/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkupKindInfo } from './markup-kind-info';
import { ReviewOptions } from './review-options';
import { DeclarationField } from './declaration-field';
import { FeedbackAspect } from './feedback-aspect';
import { Edition } from './edition';
import { MarkupColourInfo } from './markup-colour-info';
import { OccupancyGroup } from './occupancy-group';
import { CalibrationKnob } from './calibration-knob';
import { DispositionInfo } from './disposition-info';
import { AbstentionKindInfo } from './abstention-kind-info';
import { MailStatus } from './mail-status';
import { DeclarationGroup } from './declaration-group';
import { TrainingStatus } from './training-status';


export interface ConfigResponse { 
    /**
     * How `webapp.abstentions` classifies a rule that declined to run, and what it says should be done about each class.
     */
    abstention_kinds?: Array<AbstentionKindInfo>;
    /**
     * Upload formats this deployment admits, decided from a file\'s bytes rather than its name: `pdf`, and `dxf` and `zip` (of drawings) always; `dwg` only where a DWG converter is installed.
     */
    accepted_formats?: Array<ConfigResponseAcceptedFormatsEnum>;
    /**
     * Whether this deployment reads sheets with the AI reader (`FBC_AI_READING=on` with a key). Rules are pure Python either way.
     */
    ai_reading?: boolean;
    /**
     * Whether a reviewer model checks each result and may send sheets back to be read again, for at most three passes. Only ever on with AI reading; `FBC_AI_REVIEW=off` turns it off.
     */
    ai_review?: boolean;
    /**
     * Whether a DWG converter is installed here. Without one a DXF, or a zip of DXFs, is still read; a DWG is refused at upload.
     */
    cad_available?: boolean;
    /**
     * Every lever the overlay has. The closed list this publishes is what makes the triage split decidable rather than a judgement.
     */
    calibration_knobs: Array<CalibrationKnob>;
    /**
     * The whole questionnaire, as data. Adding a field or an enum value in `fbcreview/declaration_schema.py` reaches the client through here with no frontend change.
     */
    declaration_fields: Array<DeclarationField>;
    /**
     * Question groups, in the order the form should show them.
     */
    declaration_groups: Array<DeclarationGroup>;
    /**
     * Every rule any declaration field unlocks, deduplicated.
     */
    declaration_unlockable: Array<string>;
    defaults: ReviewOptions;
    dispositions: Array<DispositionInfo>;
    editions: Array<Edition>;
    /**
     * The whole feedback taxonomy, as data. Adding a verdict in `webapp/feedback_schema.py` reaches the client through here with no frontend change — the same contract the declaration questionnaire has.
     */
    feedback_aspects: Array<FeedbackAspect>;
    mail: MailStatus;
    /**
     * What each markup colour means. Semantic categories a reader sorts a submitted pass by, not a paint box.
     */
    markup_colours?: Array<MarkupColourInfo>;
    markup_kinds: Array<MarkupKindInfo>;
    max_pages: number;
    max_upload_mb: number;
    occupancy_groups: Array<OccupancyGroup>;
    retain_days: number;
    /**
     * Rule ids registered in this build.
     */
    rules: Array<string>;
    /**
     * Severity floor choices, most severe first.
     */
    severities: Array<ConfigResponseSeveritiesEnum>;
    /**
     * Ordered stage labels a running job moves through.
     */
    stages: Array<string>;
    training: TrainingStatus;
}
export enum ConfigResponseAcceptedFormatsEnum {
    Pdf = 'pdf',
    Dwg = 'dwg',
    Dxf = 'dxf',
    Zip = 'zip'
};
export enum ConfigResponseSeveritiesEnum {
    Critical = 'CRITICAL',
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW'
};



