/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConvertedPage { 
    note?: string;
    ocr_chars: number;
    page: number;
    seconds: number;
    traced_segments: number;
}

