/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConvertedPage } from './converted-page';


/**
 * What the raster rebuild actually recovered.  Reported rather than summarised away: if OCR found 40 characters on a sheet, the review that follows is thin and the person needs to know why.
 */
export interface ConversionReport { 
    converted_pages: Array<ConvertedPage>;
    ocr_used: boolean;
    recovered_chars: number;
    seconds: number;
    /**
     * Optional-content group the traced linework is written to. Deliberately not named after any semantic CAD layer — tracing recovers lines, not what they mean.
     */
    traced_layer: string;
    traced_segments: number;
    vectorise_used: boolean;
}

