/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DecisionRequest { 
    decision: DecisionRequestDecisionEnum;
    note?: string;
}
export enum DecisionRequestDecisionEnum {
    Accept = 'accept',
    Reject = 'reject',
    Action = 'action'
};



