/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDeclaration } from './project-declaration';
import { ReconciledField } from './reconciled-field';


/**
 * What was submitted and what the drawings said back. The audit trail.
 */
export interface DeclarationReport { 
    answered: number;
    declaration: ProjectDeclaration;
    fields: Array<ReconciledField>;
    total_fields: number;
}

