/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeclarationTolerance } from './declaration-tolerance';


/**
 * One question, in both vocabularies.  The client renders whatever this describes and must not carry a copy of any label, help text or enum value: a code label that exists in two places will drift, and a wrong code label is a liability rather than a typo.
 */
export interface DeclarationField { 
    choice_labels?: { [key: string]: string; } | null;
    choices?: Array<string> | null;
    group: string;
    key: string;
    kind: DeclarationFieldKindEnum;
    pro_help: string;
    pro_label: string;
    simple_help: string;
    simple_label: string;
    tolerance?: DeclarationTolerance | null;
    unit?: string;
    /**
     * Rule ids this answer enables. The client divides by these to say how many checks will stand down without it.
     */
    unlocks?: Array<string>;
}
export enum DeclarationFieldKindEnum {
    Enum = 'enum',
    Bool = 'bool',
    Number = 'number',
    Integer = 'integer',
    Text = 'text'
};



