/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * How far apart two numbers may be before they count as disagreeing.  Effective tolerance is `max(abs, rel * value)`. Rounding on a drawing is not a conflict; a different governing row is.
 */
export interface DeclarationTolerance { 
    abs: number;
    rel: number;
}

