/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum Disposition {

    Confirmation = 'confirmation',

    AutoTunable = 'auto_tunable',

    NeedsComponent = 'needs_component',

    Escalate = 'escalate'
}

