/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DispositionInfo { 
    key: DispositionInfoKeyEnum;
    label: string;
}
export enum DispositionInfoKeyEnum {
    Confirmation = 'confirmation',
    AutoTunable = 'auto_tunable',
    NeedsComponent = 'needs_component',
    Escalate = 'escalate'
};



