/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * V4 signed URLs, fetched straight from Cloud Storage by the browser.
 */
export interface Downloads { 
    expires_at: string;
    findings_json: string;
    /**
     * The drawing with the findings drawn into it on layers FBC-REVIEW (what needs action), FBC-REVIEW-VERIFIED (what was checked and found sufficient) and FBC-REVIEW-TEXT, as zipped DXF. Empty unless the upload was a drawing, and empty if writing it failed — the marked-up PDF is the review of record.
     */
    markup_dxf?: string;
    markup_pdf: string;
    /**
     * The PDF the engine read, which the in-app viewer renders: the set as uploaded, or for a drawing upload the sheets plotted from it — every finding\'s `rect` is in this file\'s page space. The viewer draws the findings itself as an overlay rather than rendering `markup_pdf`; otherwise every marker would be drawn twice, once burnt into the page and once interactively, and neither could be turned off.
     */
    source_pdf?: string;
}

