/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Edition { 
    /**
     * False editions are listed and disabled, not hidden.
     */
    available: boolean;
    id: string;
    label: string;
}

