/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorDetail { 
    /**
     * Stable machine-readable code, e.g. `rate_limited`.
     */
    code: string;
    /**
     * Prose safe to show a person.
     */
    message: string;
}

