/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';


/**
 * The only shape any failure takes.
 */
export interface ErrorResponse { 
    error: ErrorDetail;
}

