/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TriageResult } from './triage-result';
import { Finding } from './finding';
import { Markup } from './markup';


export interface Feedback { 
    answers?: { [key: string]: string; };
    /**
     * Whether this landed in the submitter\'s own training profile. Production is untouched until the owner promotes.
     */
    applied_to_candidate?: boolean;
    comment?: string;
    created_at: string;
    decided_at?: string | null;
    decided_by?: string;
    decision_note?: string;
    disposition: FeedbackDispositionEnum;
    email?: string;
    filename?: string;
    finding?: Finding | null;
    finding_fid?: string;
    id: string;
    issue_url?: string;
    job_id: string;
    markup?: Markup | null;
    markup_id?: string;
    page?: number;
    rationale?: string;
    rule_id?: string;
    sheet?: string;
    state: FeedbackStateEnum;
    subject: FeedbackSubjectEnum;
    triage: TriageResult;
}
export enum FeedbackDispositionEnum {
    Confirmation = 'confirmation',
    AutoTunable = 'auto_tunable',
    NeedsComponent = 'needs_component',
    Escalate = 'escalate'
};
export enum FeedbackStateEnum {
    New = 'new',
    Accepted = 'accepted',
    Rejected = 'rejected',
    Actioned = 'actioned'
};
export enum FeedbackSubjectEnum {
    Finding = 'finding',
    Coverage = 'coverage'
};



