/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeedbackVerdict } from './feedback-verdict';
import { FeedbackSubject } from './feedback-subject';


/**
 * One separable dimension of review quality.
 */
export interface FeedbackAspect { 
    help: string;
    key: string;
    label: string;
    required: boolean;
    subject: FeedbackSubject;
    verdicts: Array<FeedbackVerdict>;
}



