/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum FeedbackSubject {

    Finding = 'finding',

    Coverage = 'coverage',

    Abstention = 'abstention',

    Sweep = 'sweep'
}

