/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One answer to one aspect, as the form should offer it.  Deliberately carries no hint of which calibration lever it moves. The client describes what a person saw; `webapp.triage` decides what that implies. A UI that showed the lever would invite people to pick the outcome they want instead of the observation they made.
 */
export interface FeedbackVerdict { 
    help: string;
    key: string;
    label: string;
    /**
     * `good` verdicts are real signal, not an opt-out: they are what stops one dissent from moving a rule fifty people corroborated.
     */
    polarity: FeedbackVerdictPolarityEnum;
}
export enum FeedbackVerdictPolarityEnum {
    Good = 'good',
    Defect = 'defect'
};



