/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TriageResult } from './triage-result';


/**
 * What the submitter is told back.  The triage verdict is returned rather than hidden: someone who reports a misread table should be told immediately that it needs engine work and is not a knob, instead of watching nothing happen.
 */
export interface FeedbackAccepted { 
    applied_to_candidate: boolean;
    candidate_version?: number;
    id: string;
    message: string;
    triage: TriageResult;
}

