/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeedbackSubject } from './feedback-subject';


/**
 * One piece of feedback about one thing.  `answers` is the structured part and is what gets triaged. `comment` is the residue — everything the taxonomy did not ask about — and a submission that carries one always reaches a person, because prose nobody has read cannot be routed deterministically.
 */
export interface FeedbackRequest { 
    /**
     * Aspect key to verdict key, validated against the taxonomy `/api/config` publishes. An unknown key is a 400 naming it.
     */
    answers?: { [key: string]: string; };
    comment?: string;
    finding_fid?: string;
    markup_id?: string;
    /**
     * The rule an abstention-subject submission is about. Checked against the abstentions this review actually recorded — a rule id the review did not stand down on is a 404, so the anchor cannot be invented by the client any more than a finding id can.
     */
    rule_id?: string;
    subject?: FeedbackSubject;
}



