/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeedbackVerdict } from './feedback-verdict';


/**
 * One separable dimension of review quality.
 */
export interface FeedbackAspect { 
    help: string;
    key: string;
    label: string;
    required: boolean;
    subject: FeedbackAspectSubjectEnum;
    verdicts: Array<FeedbackVerdict>;
}
export enum FeedbackAspectSubjectEnum {
    Finding = 'finding',
    Coverage = 'coverage'
};



