/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FindingAiRevision } from './finding-ai-revision';
import { FindingEvidence } from './finding-evidence';


/**
 * One rule outcome. Mirrors `fbcreview.rules.Finding`, plus what the viewer needs.
 */
export interface Finding { 
    action?: string;
    /**
     * Present when the AI result review revised or raised this finding. Absent on every finding the rules alone decided.
     */
    ai_revision?: FindingAiRevision | null;
    anchor: string;
    /**
     * What the finding rests on. `declaration` means the drawings do not state the value it depends on, and the card says so — the markup must never attribute to the drawings something the drawings do not say.
     */
    basis?: FindingBasisEnum;
    body?: string;
    checked: string;
    code: string;
    discipline: string;
    /**
     * The readings the rule\'s inputs rest on, and which reader found each.
     */
    evidence?: Array<FindingEvidence>;
    fid: string;
    hit?: number;
    /**
     * Unique within one review. `fid` is not — two under-width doors are two H-03s — so anything the client keys, tracks or selects uses this. Empty on a review written before it existed; fall back to `fid`.
     */
    key?: string;
    page: number;
    /**
     * Where to draw the marker: [x0, y0, x1, y1] in pdf.js viewport space at scale 1 on the uploaded set\'s page (points, origin top-left, rotation applied). Null when it could not be placed; `anchor` and `hit` remain the fallback.
     */
    rect?: Array<number> | null;
    result: string;
    rule_id: string;
    /**
     * Which reading produced this. `both` means it came out the same whether the set was evaluated as drawn or as declared, which is the common case. `as_drawn` means it appeared only against the drawings; `as_declared` only against the declaration.
     */
    scenario?: FindingScenarioEnum;
    severity: FindingSeverityEnum;
    sheet: string;
    status: FindingStatusEnum;
    title: string;
}
export enum FindingBasisEnum {
    Drawings = 'drawings',
    Declaration = 'declaration',
    Both = 'both'
};
export enum FindingScenarioEnum {
    Both = 'both',
    AsDrawn = 'as_drawn',
    AsDeclared = 'as_declared'
};
export enum FindingSeverityEnum {
    Critical = 'CRITICAL',
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    Verified = 'VERIFIED',
    Measured = 'MEASURED'
};
export enum FindingStatusEnum {
    Open = 'OPEN',
    Pass = 'PASS',
    Conflict = 'CONFLICT'
};



