/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One rule outcome. Mirrors `fbcreview.rules.Finding`.
 */
export interface Finding { 
    action?: string;
    anchor: string;
    body?: string;
    checked: string;
    code: string;
    discipline: string;
    fid: string;
    hit?: number;
    page: number;
    result: string;
    rule_id: string;
    severity: FindingSeverityEnum;
    sheet: string;
    status: FindingStatusEnum;
    title: string;
}
export enum FindingSeverityEnum {
    Critical = 'CRITICAL',
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW',
    Verified = 'VERIFIED',
    Measured = 'MEASURED'
};
export enum FindingStatusEnum {
    Open = 'OPEN',
    Pass = 'PASS'
};



