/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One reading a finding rests on: the value, the words as printed, and where.  Written by `fbcreview/payload.py`. `method` says which reader found it — `pair`, `line` and `table` are the layout reader; `ai` is the AI sheet reader, whose readings are used only after the quote has been found on the sheet; `cad` is a block attribute read from an uploaded drawing — and `note` says so in words a card can show. `basis` says whether the value is printed (`stated`), a table\'s own sum (`tabulated`), worked out (`computed`) or measured off the geometry (`measured`), so an estimate never reads as a statement.
 */
export interface FindingEvidence { 
    /**
     * `stated`, `tabulated`, `computed` or `measured`.
     */
    basis?: string;
    confidence: string;
    /**
     * The catalog field, e.g. `egress.common_path`.
     */
    field: string;
    method: string;
    note?: string;
    /**
     * 0-based, like `Finding.page`.
     */
    page: number;
    /**
     * The words the value was read from, as printed.
     */
    quote: string;
    /**
     * Where it is printed: pdf.js viewport space at scale 1 on the source page.
     */
    rect?: Array<number> | null;
    /**
     * `required`, `provided`, or empty.
     */
    role?: string;
    sheet: string;
    /**
     * Every sheet that states the same value.
     */
    sheets?: Array<string>;
    /**
     * The value as a card shows it.
     */
    value: string;
}

