/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What the AI result review did to a finding. See `fbcreview/ai/review.py`.
 */
export interface FindingAiRevision { 
    /**
     * Which fields a revision changed.
     */
    changed?: Array<string>;
    /**
     * `add` when the AI review raised the finding itself; `revise` when it changed one a rule produced.
     */
    op: FindingAiRevisionOpEnum;
    /**
     * 1-based page of the quote.
     */
    page?: number | null;
    /**
     * The pass that last changed it (1-3).
     */
    pass: number;
    /**
     * Sheet text the edit rests on, as printed — found on the page before the edit applied.
     */
    quote?: string;
    /**
     * Why, in the reviewer\'s words. Also appended to `result`.
     */
    reason: string;
    /**
     * The status and severity before the revision.
     */
    was?: { [key: string]: string; };
}
export enum FindingAiRevisionOpEnum {
    Revise = 'revise',
    Add = 'add'
};



