/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Deliberately cheap: no Firestore or Cloud Storage call. Cloud Run\'s startup probe hits this.
 */
export interface Health { 
    ok: boolean;
    service: string;
    version: string;
}

