/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Deliberately cheap: no Firestore or Cloud Storage call. Cloud Run\'s startup probe hits this.
 */
export interface Health { 
    /**
     * Whether this deployment demands a Firebase ID token. False only on a deliberately open build. The client reads it here rather than inferring it, because guessing wrong in either direction is bad: guess `true` on an open deployment and the tool is unreachable; guess `false` on a real one and every request 401s behind a UI that claims you are signed in.
     */
    auth_required?: boolean;
    ok: boolean;
    service: string;
    version: string;
}

