/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One past review, as the history list shows it.  Deliberately not the whole `Job`. A list of thirty rows does not need thirty sets of signed download URLs, and minting them costs a round trip each — the client asks for `GET /api/jobs/{id}` when a row is actually opened.
 */
export interface HistoryEntry { 
    /**
     * Findings by severity, from the stored summary. Empty until done.
     */
    counts?: { [key: string]: number; };
    created_at: string;
    /**
     * How many declaration questions were answered.
     */
    declared_fields?: number;
    edition?: string;
    error?: string | null;
    filename: string;
    finished_at?: string | null;
    id: string;
    open_findings?: number;
    pages?: number;
    project_name?: string;
    state: HistoryEntryStateEnum;
}
export enum HistoryEntryStateEnum {
    Queued = 'queued',
    Running = 'running',
    Done = 'done',
    Error = 'error'
};



