/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoryEntry } from './history-entry';


/**
 * The caller\'s own reviews, newest first. Never anyone else\'s.
 */
export interface HistoryResponse { 
    entries: Array<HistoryEntry>;
}

