/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IssueCreated { 
    feedback_id: string;
    status: string;
    /**
     * Empty when GitHub is not configured on this server.
     */
    url: string;
}

