/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDeclaration } from './project-declaration';
import { ReviewOptions } from './review-options';
import { Summary } from './summary';
import { ConversionReport } from './conversion-report';
import { Downloads } from './downloads';
import { SourceProfile } from './source-profile';


export interface Job { 
    bytes: number;
    /**
     * Present when scanned sheets were rebuilt.
     */
    conversion?: ConversionReport | null;
    created_at: string;
    /**
     * What was submitted with the review, if anything.
     */
    declaration?: ProjectDeclaration | null;
    /**
     * Present only while state is `done`.
     */
    downloads?: Downloads | null;
    elapsed_seconds: number;
    error?: string | null;
    error_code?: string | null;
    /**
     * Basename as uploaded. Never a path.
     */
    filename: string;
    finished_at?: string | null;
    id: string;
    options: ReviewOptions;
    pages?: number | null;
    /**
     * What kind of PDF was uploaded, measured at admission.
     */
    source?: SourceProfile | null;
    /**
     * Index into `stages`.
     */
    stage: number;
    stage_label: string;
    stages: Array<string>;
    started_at?: string | null;
    state: JobStateEnum;
    summary?: Summary | null;
}
export enum JobStateEnum {
    Queued = 'queued',
    Running = 'running',
    Done = 'done',
    Error = 'error'
};



