/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CadReport } from './cad-report';
import { ProjectDeclaration } from './project-declaration';
import { ReviewOptions } from './review-options';
import { CalibrationReport } from './calibration-report';
import { Summary } from './summary';
import { ConversionReport } from './conversion-report';
import { Downloads } from './downloads';
import { AbstentionDiagnosis } from './abstention-diagnosis';
import { SourceProfile } from './source-profile';


export interface Job { 
    bytes: number;
    /**
     * Present once a drawing upload has been read; null for a PDF.
     */
    cad?: CadReport | null;
    /**
     * What the calibration overlay did to this review. Present on any finished review, including one where it changed nothing.
     */
    calibration?: CalibrationReport | null;
    /**
     * Present when scanned sheets were rebuilt.
     */
    conversion?: ConversionReport | null;
    created_at: string;
    /**
     * What was submitted with the review, if anything.
     */
    declaration?: ProjectDeclaration | null;
    /**
     * Root causes that would account for several of this review\'s abstentions at once. Computed on read from the abstentions and the source profile, so an old review gets one too. Empty when nothing in the record supports a claim.
     */
    diagnosis?: Array<AbstentionDiagnosis>;
    /**
     * Present only while state is `done`.
     */
    downloads?: Downloads | null;
    elapsed_seconds: number;
    error?: string | null;
    error_code?: string | null;
    /**
     * Basename as uploaded. Never a path.
     */
    filename: string;
    finished_at?: string | null;
    id: string;
    options: ReviewOptions;
    pages?: number | null;
    /**
     * The review this one re-ran, when it re-ran one. Set by `POST /api/jobs/{id}/rerun`; null on a review of a freshly uploaded set. The two are separate reviews on purpose — a review is a dated statement, and the earlier one is not edited.
     */
    rerun_of?: string | null;
    /**
     * What kind of PDF the engine reads: measured at admission for a PDF upload, and once it has been plotted for a drawing.
     */
    source?: SourceProfile | null;
    /**
     * What was uploaded, decided from its bytes. A drawing (`dwg`, `dxf`, `zip`) is plotted to PDF by the review itself, and `source`, `pages` and `downloads.source_pdf` then describe that plot.
     */
    source_format?: JobSourceFormatEnum;
    /**
     * Index into `stages`.
     */
    stage: number;
    stage_label: string;
    stages: Array<string>;
    started_at?: string | null;
    state: JobStateEnum;
    summary?: Summary | null;
}
export enum JobSourceFormatEnum {
    Pdf = 'pdf',
    Dwg = 'dwg',
    Dxf = 'dxf',
    Zip = 'zip'
};
export enum JobStateEnum {
    Queued = 'queued',
    Running = 'running',
    Done = 'done',
    Error = 'error'
};



