/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Markup } from './markup';


/**
 * A whole annotated pass, in one document.  What a reviewer takes away at the end of a session and what the owner reads when one is submitted. Deliberately the same payload for both: an export somebody can inspect before they send it is an export they will trust, and two different shapes would drift.  Geometry is carried per markup because it is what makes an annotation checkable — \"sheet 12, this box, this comment\" can be found again. It is in PDF points, the same space the viewer draws in.
 */
export interface MarkupExport { 
    /**
     * How many carry a written comment.
     */
    commented?: number;
    /**
     * How many of each kind, for the summary line.
     */
    counts?: { [key: string]: number; };
    exported_at: string;
    /**
     * Empty on an open-access deployment.
     */
    exported_by?: string;
    filename?: string;
    job_id: string;
    markups: Array<Markup>;
    project_name?: string;
    /**
     * Sheets carrying at least one annotation.
     */
    sheets?: Array<number>;
    text?: string;
}

