/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkupKind } from './markup-kind';
import { MarkupGeometry } from './markup-geometry';


export interface Markup { 
    colour?: string;
    comment?: string;
    created_at: string;
    finding_fid?: string;
    geometry: MarkupGeometry;
    id: string;
    job_id: string;
    kind: MarkupKind;
    page: number;
    sheet?: string;
}



