/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Where a markup sits, in PDF user space.  PDF points, not screen pixels, and not a fraction of the page. The viewer zooms and the window resizes; the drawing does not. Storing device coordinates would make every markup wrong at a different zoom level, and storing fractions would lose precision on a 24x36 sheet where a door tag is a few points across.
 */
export interface MarkupGeometry { 
    /**
     * Freehand and arrow paths, as [[x, y], ...] in the same space.
     */
    points?: Array<Array<number>>;
    x0?: number;
    x1?: number;
    y0?: number;
    y1?: number;
}

