/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum MarkupKind {

    Highlight = 'highlight',

    Box = 'box',

    Arrow = 'arrow',

    Strikeout = 'strikeout',

    Freehand = 'freehand',

    Note = 'note'
}

