/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkupGeometry } from './markup-geometry';


export interface Markup { 
    colour?: string;
    comment?: string;
    created_at: string;
    finding_fid?: string;
    geometry: MarkupGeometry;
    id: string;
    job_id: string;
    kind: MarkupKindEnum;
    page: number;
    sheet?: string;
}
export enum MarkupKindEnum {
    Highlight = 'highlight',
    Box = 'box',
    Arrow = 'arrow',
    Strikeout = 'strikeout',
    Freehand = 'freehand',
    Note = 'note'
};



