/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What a markup colour means.  Served rather than hard-coded in the client for the same reason the taxonomy is: these are semantic categories a reader sorts by, not decoration, and there must be one definition of what purple means.
 */
export interface MarkupColourInfo { 
    help: string;
    /**
     * The swatch, for the palette and the overlay.
     */
    hex: string;
    key: string;
    label: string;
}

