/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarkupKind } from './markup-kind';


export interface MarkupKindInfo { 
    help: string;
    key: MarkupKind;
    label: string;
}



