/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OccupancyGroup { 
    /**
     * Value submitted with a review, e.g. `A-3`.
     */
    id: string;
    label: string;
}

