/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One declaration answer the drawings already state.  A suggestion, never a decision. The applicant confirms or overrides it, and what they submit is what gets declared — the reconciliation is only worth running if the two sides stay independent, and a silently auto-accepted value would make every field agree with itself.
 */
export interface PrefilledField { 
    confidence: string;
    /**
     * A declaration field key, as `/api/config` publishes it.
     */
    key: string;
    note?: string;
    page?: number | null;
    /**
     * Where on the set it was read, e.g. \"G-0 project data\".
     */
    source: string;
    /**
     * Rendered as the field\'s control holds it, never typed.
     */
    value: string;
}

