/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrefilledField } from './prefilled-field';
import { SourceProfile } from './source-profile';


/**
 * What a set states about itself, read without starting a review.
 */
export interface PrefillResponse { 
    bytes: number;
    /**
     * Only fields the drawings actually state. A set whose code data block is a pasted picture yields very few, which is the honest answer for that set and exactly the case the declaration exists to cover.
     */
    fields: Array<PrefilledField>;
    filename: string;
    pages: number;
    source: SourceProfile;
}

