/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * What the applicant says the building is, answered before uploading.  Every field is optional and `null` means unanswered. There is deliberately no \"unknown\" sentinel: a rule that receives `null` abstains, and it can never mistake a placeholder for an answer.  Mirrors `fbcreview.declaration.ProjectDeclaration`. Values are validated against `fbcreview.declaration_schema` before a review starts, so an enum value this build does not know is a 400 naming the field rather than a silently dropped answer.
 */
export interface ProjectDeclaration { 
    building_area_sf?: number | null;
    code_edition?: string | null;
    construction_type?: string | null;
    exposure_category?: string | null;
    height_ft?: number | null;
    jurisdiction?: string | null;
    mixed_occupancy?: boolean | null;
    occupancy_group?: string | null;
    risk_category?: string | null;
    separation_method?: string | null;
    sprinkler_system?: string | null;
    stories?: number | null;
    total_area_sf?: number | null;
    wind_speed_mph?: number | null;
    zoning?: string | null;
}

