/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Escalated feedback as a runnable prompt.  Returned as a typed body rather than `text/markdown` so the generated client carries the type, as everything else here does.
 */
export interface PromptExport { 
    feedback_id: string;
    /**
     * Suggested name under docs/, in the house style.
     */
    filename: string;
    markdown: string;
}

