/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A pasted image large enough to plausibly hold a table.
 */
export interface RasterRegion { 
    coverage: number;
    megapixels: number;
    x0: number;
    x1: number;
    y0: number;
    y1: number;
}

