/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One field, with what each source said about it and how they compare.
 */
export interface ReconciledField { 
    /**
     * Rendered for display.
     */
    declared?: string | null;
    drawn?: string | null;
    /**
     * The sheet the drawn value was read from.
     */
    drawn_source?: string | null;
    field: string;
    note?: string;
    state: ReconciledFieldStateEnum;
}
export enum ReconciledFieldStateEnum {
    Corroborated = 'CORROBORATED',
    Conflict = 'CONFLICT',
    DeclaredOnly = 'DECLARED_ONLY',
    DrawnOnly = 'DRAWN_ONLY',
    Unknown = 'UNKNOWN'
};



