/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectDeclaration } from './project-declaration';


/**
 * Review the same set again, having answered more of the declaration.  The commonest abstention on a real submittal is a rule standing down for want of a value that neither the drawings nor the declaration carry. Until this existed the only remedy was to upload the file again and re-answer the whole questionnaire, which is why nobody did it and the abstention stayed.  The set itself is never re-sent: the PDF is already in the bucket and the admission profile is already on the record, so this costs a re-run of the engine and nothing else.
 */
export interface RerunRequest { 
    /**
     * Override the rebuild-scanned-sheets option. Omitted keeps what the original review ran with.
     */
    convert_raster?: boolean | null;
    /**
     * The declaration for the new review. Merged over the original\'s — a field omitted here keeps whatever the first review was given, and nothing that was already answered has to be typed again.
     */
    declaration?: ProjectDeclaration;
}

