/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The review parameters. Mirrors `fbcreview.options.ReviewOptions`.
 */
export interface ReviewOptions { 
    edition?: string;
    /**
     * Inert unless SMTP is configured on the server. Not surfaced in the web client.
     */
    email_to?: Array<string>;
    include_measured?: boolean;
    include_verified?: boolean;
    min_severity?: ReviewOptionsMinSeverityEnum;
    notes?: string;
    occupancy_group?: string;
    project_name?: string;
    sprinklered?: boolean;
}
export enum ReviewOptionsMinSeverityEnum {
    Critical = 'CRITICAL',
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW'
};



