/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The review parameters. Mirrors `fbcreview.options.ReviewOptions`.
 */
export interface ReviewOptions { 
    /**
     * Rebuild scanned sheets before reviewing: OCR to recover a text layer, and trace the linework into real vector paths. Off by default because it turns a two-second review into a multi-minute one. Recovers text, not meaning — traced lines carry no CAD layer names, so geometric rules still abstain.
     */
    convert_raster?: boolean;
    edition?: string;
    /**
     * Inert unless SMTP is configured on the server. Not surfaced in the web client.
     */
    email_to?: Array<string>;
    include_measured?: boolean;
    include_verified?: boolean;
    min_severity?: ReviewOptionsMinSeverityEnum;
    notes?: string;
    /**
     * Deprecated. Occupancy group is a fact about the building, not a review setting, and belongs in the project declaration. Sent explicitly, it seeds `declaration.occupancy_group` when the declaration does not state one; left at its default it is ignored and nothing is assumed.
     */
    occupancy_group?: string;
    project_name?: string;
    /**
     * Deprecated, as `occupancy_group`. Sent explicitly it seeds `declaration.sprinkler_system` as an NFPA 13 system or none.
     */
    sprinklered?: boolean;
}
export enum ReviewOptionsMinSeverityEnum {
    Critical = 'CRITICAL',
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW'
};



