/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RuleCalibration { 
    /**
     * Reviewers who said this rule got something right.
     */
    confirmations?: number;
    drop_verified?: boolean;
    enabled?: boolean;
    note?: string;
    rule_id: string;
    scope_basis?: Array<string>;
    scope_occupancy?: Array<string>;
    severity_cap?: RuleCalibrationSeverityCapEnum | null;
    severity_floor?: RuleCalibrationSeverityFloorEnum | null;
    severity_shift?: number;
    weight?: number;
}
export enum RuleCalibrationSeverityCapEnum {
    Critical = 'CRITICAL',
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW'
};
export enum RuleCalibrationSeverityFloorEnum {
    Critical = 'CRITICAL',
    High = 'HIGH',
    Medium = 'MEDIUM',
    Low = 'LOW'
};



