/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * One sheet of the set, as the title block names it.  The viewer\'s navigator is the reason this exists. `pages` alone gives it \"3 of 15\", which is not what anybody working through a permit set says to anybody else — they say M.001, or A-2. The engine already reads the sheet number off the title block to key its findings, so the labels are not a new claim about the drawings; they are the same reading, carried far enough forward to be navigable.  A sheet whose number could not be read keeps its page number, exactly as `fbcreview.facts.ProjectFacts.sheet_code` does — `p7` rather than a guess.
 */
export interface SheetRef { 
    /**
     * Sheet number off the title block, e.g. \"M.001\".
     */
    code: string;
    /**
     * G / A / M / E / P.
     */
    discipline?: string;
    /**
     * 1-based, as the viewer numbers pages.
     */
    page: number;
    /**
     * False when the sheet number could not be read and `code` is a page number standing in for it.
     */
    read?: boolean;
    /**
     * Sheet title, where one was read.
     */
    title?: string;
}

