/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Measured, not guessed: drawing-primitive count, live character count and how much of the page is covered by raster images.
 */
export interface SheetProfile { 
    image_count: number;
    image_coverage: number;
    kind: SheetProfileKindEnum;
    live_chars: number;
    page: number;
    reason: string;
    vector_items: number;
}
export enum SheetProfileKindEnum {
    Vector = 'vector',
    Hybrid = 'hybrid',
    Raster = 'raster',
    Blank = 'blank'
};



