/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SheetProfile } from './sheet-profile';


/**
 * Whether this set is readable, and which sheets are not.  A scanned sheet produces no findings, and no findings reads as a clean sheet. Publishing this lets the client say \"not checked\" where the truth is \"could not be read\".
 */
export interface SourceProfile { 
    cad_layers: number;
    kind: SourceProfileKindEnum;
    /**
     * Sheets that are wholly images.
     */
    raster_pages?: Array<number>;
    /**
     * Readable sheets that nonetheless paste part of the drawing in as an image. A code-analysis table pasted that way is pixels, and needs OCR.
     */
    region_pages?: Array<number>;
    reviewable_pages: number;
    sheets: Array<SheetProfile>;
    summary: string;
}
export enum SourceProfileKindEnum {
    Vector = 'vector',
    Mixed = 'mixed',
    Raster = 'raster',
    Blank = 'blank'
};



