/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Abstention } from './abstention';


/**
 * Counts and provenance for a finished review.  The findings themselves are deliberately not carried here: a Firestore document is capped at 1 MiB and a large set\'s finding bodies can approach it. They live in `findings.json` in the bucket and are fetched from the signed URL.
 */
export interface Summary { 
    abstentions: Array<Abstention>;
    annotations: number;
    cad_layers: number;
    /**
     * Finding count keyed by severity.
     */
    counts: { [key: string]: number; };
    findings_count: number;
    marked: number;
    open: number;
    pages: number;
    pdf_bytes: number;
    pdf_name: string;
    rules_run: number;
    scale_pages: number;
    sheets: number;
    verified: number;
}

