/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Hand a marked-up pass over for review.  Carries no markup: the server already holds every annotation on this job for this user, and letting the client post its own list would let it submit a pass that never existed. `answers` and `comment` are the same shape every other submission uses, validated against the `sweep` aspect.
 */
export interface SweepRequest { 
    answers?: { [key: string]: string; };
    comment?: string;
}

