/**
 * FBC Code Review
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Whether this deployment collects feedback, and what it can do with it.
 */
export interface TrainingStatus { 
    /**
     * Whether free-text comments get summarised, and how.
     */
    assist: string;
    /**
     * How many rules the active profile changes.
     */
    calibrated_rules?: number;
    /**
     * False reproduces the service exactly as it was.
     */
    enabled: boolean;
    /**
     * Whether escalations can become issues, and where.
     */
    github: string;
    /**
     * Whether the caller may read the queue and promote a profile. Checked server-side on every admin route regardless; this is only so the client knows whether to draw the link.
     */
    is_owner: boolean;
    profile_label?: string;
    /**
     * The calibration version production uses.
     */
    profile_version: number;
}

